package com.example.demo.model.enums;

public enum ErrorEnum {
    FILE_NOT_FOUND("FILE_NOT_FOUND"),
    FILE_IS_EMPTY("FILE_IS_EMPTY"),
    FILE_NAME_IS_EMPTY("FILE_NAME_IS_EMPTY"),
    WRONG_DATA_FORMAT("WRONG_DATA_FORMAT"),
    FILE_ALREADY_EXISTS("FILE_ALREADY_EXISTS"),
    FILE_NAME_NOT_SUPPORTED("FILE_NAME_NOT_SUPPORTED"),
    FILE_EXTENSION_NOT_SUPPORTED("FILE_EXTENSION_NOT_SUPPORTED");

    ErrorEnum(String s) {
    }
}
